### ISSUE TITLE
MySQLDataTruncation Exception when submitting a test file

### ISSUE THREAD

**Issue by EvgenyKarataev** [ColFusion/ColfusionServer#8]
Tried to submit test ABC file, but at the end of the wizard got this errors in the console log on server:

```
19:46:04.687 [1] ERROR edu.pitt.sis.exp.colfusion.dal.utils.HibernateUtil - commitTransaction failed
org.hibernate.exception.DataException: could not execute statement
    at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:69) ~[hibernate-core-4.3.4.Final.jar:4.3.4.Final]
    at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:49) ~[hibernate-core-4.3.4.Final.jar:4.3.4.Final]
    at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:126) ~[hibernate-core-4.3.4.Final.jar:4.3.4.Final]
    at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:112) ~[hibernate-core-4.3.4.Final.jar:4.3.4.Final]
    at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:190) ~[hibernate-core-4.3.4.Final.jar:4.3.4.Final]
    at org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch.addToBatch(NonBatchingBatch.java:62) ~[hibernate-core-4.3.4.Final.jar:4.3.4.Final]
    at org.hibernate.persister.entity.AbstractEntityPersister.update(AbstractEntityPersister.java:3281) ~[hibernate-core-4.3.4.Final.jar:4.3.4.Final]
    at org.hibernate.persister.entity.AbstractEntityPersister.updateOrInsert(AbstractEntityPersister.java:3183) ~[hibernate-core-4.3.4.Final.jar:4.3.4.Final]
    at org.hibernate.persister.entity.AbstractEntityPersister.update(AbstractEntityPersister.java:3525) ~[hibernate-core-4.3.4.Final.jar:4.3.4.Final]
    at org.hibernate.action.internal.EntityUpdateAction.execute(EntityUpdateAction.java:158) ~[hibernate-core-4.3.4.Final.jar:4.3.4.Final]
    at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:461) ~[hibernate-core-4.3.4.Final.jar:4.3.4.Final]
    at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:347) ~[hibernate-core-4.3.4.Final.jar:4.3.4.Final]
    at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:350) ~[hibernate-core-4.3.4.Final.jar:4.3.4.Final]
    at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:56) ~[hibernate-core-4.3.4.Final.jar:4.3.4.Final]
    at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1222) ~[hibernate-core-4.3.4.Final.jar:4.3.4.Final]
    at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:425) ~[hibernate-core-4.3.4.Final.jar:4.3.4.Final]
    at org.hibernate.engine.transaction.internal.jdbc.JdbcTransaction.beforeTransactionCommit(JdbcTransaction.java:101) ~[hibernate-core-4.3.4.Final.jar:4.3.4.Final]
    at org.hibernate.engine.transaction.spi.AbstractTransactionImpl.commit(AbstractTransactionImpl.java:177) ~[hibernate-core-4.3.4.Final.jar:4.3.4.Final]
    at edu.pitt.sis.exp.colfusion.dal.utils.HibernateUtil.commitTransaction(HibernateUtil.java:137) [colfusionserverdal-2.0-SNAPSHOT.jar:?]
    at edu.pitt.sis.exp.colfusion.dal.managers.ExecutionInfoManagerImpl.appendLog(ExecutionInfoManagerImpl.java:202) [colfusionserverdal-2.0-SNAPSHOT.jar:?]
    at edu.pitt.sis.exp.colfusion.dataLoadExecutors.DataLoadExecutorKTRImpl.changeTransformationName(DataLoadExecutorKTRImpl.java:247) [colfusionserver-2.0-SNAPSHOT.jar:?]
    at edu.pitt.sis.exp.colfusion.dataLoadExecutors.DataLoadExecutorKTRImpl.execute(DataLoadExecutorKTRImpl.java:95) [colfusionserver-2.0-SNAPSHOT.jar:?]
    at edu.pitt.sis.exp.colfusion.process.ProcessBase.run(ProcessBase.java:174) [colfusionserver-2.0-SNAPSHOT.jar:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'log' at row 1
    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4235) ~[mysql-connector-java-5.1.29.jar:?]
    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4169) ~[mysql-connector-java-5.1.29.jar:?]
    at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2617) ~[mysql-connector-java-5.1.29.jar:?]
    at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2778) ~[mysql-connector-java-5.1.29.jar:?]
    at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2834) ~[mysql-connector-java-5.1.29.jar:?]
    at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2156) ~[mysql-connector-java-5.1.29.jar:?]
    at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2441) ~[mysql-connector-java-5.1.29.jar:?]
    at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2366) ~[mysql-connector-java-5.1.29.jar:?]
    at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2350) ~[mysql-connector-java-5.1.29.jar:?]
    at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:147) ~[c3p0-0.9.2.1.jar:0.9.2.1]
    at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:187) ~[hibernate-core-4.3.4.Final.jar:4.3.4.Final]
    ... 19 more
19:46:04.691 [1] INFO  edu.pitt.sis.exp.colfusion.dal.utils.HibernateUtil - commitTransaction: commited trasaction org.hibernate.engine.transaction.internal.jdbc.JdbcTransaction@2a05ac53
19:46:04.691 [1] ERROR edu.pitt.sis.exp.colfusion.dal.managers.ExecutionInfoManagerImpl - appendLog failed HibernateException
org.hibernate.HibernateException: org.hibernate.exception.DataException: could not execute statement
    at edu.pitt.sis.exp.colfusion.dal.utils.HibernateUtil.commitTransaction(HibernateUtil.java:165) ~[colfusionserverdal-2.0-SNAPSHOT.jar:?]
    at edu.pitt.sis.exp.colfusion.dal.managers.ExecutionInfoManagerImpl.appendLog(ExecutionInfoManagerImpl.java:202) [colfusionserverdal-2.0-SNAPSHOT.jar:?]
    at edu.pitt.sis.exp.colfusion.dataLoadExecutors.DataLoadExecutorKTRImpl.changeTransformationName(DataLoadExecutorKTRImpl.java:247) [colfusionserver-2.0-SNAPSHOT.jar:?]
    at edu.pitt.sis.exp.colfusion.dataLoadExecutors.DataLoadExecutorKTRImpl.execute(DataLoadExecutorKTRImpl.java:95) [colfusionserver-2.0-SNAPSHOT.jar:?]
    at edu.pitt.sis.exp.colfusion.process.ProcessBase.run(ProcessBase.java:174) [colfusionserver-2.0-SNAPSHOT.jar:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: org.hibernate.exception.DataException: could not execute statement
    at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:69) ~[hibernate-core-4.3.4.Final.jar:4.3.4.Final]
    at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:49) ~[hibernate-core-4.3.4.Final.jar:4.3.4.Final]
    at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:126) ~[hibernate-core-4.3.4.Final.jar:4.3.4.Final]
    at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:112) ~[hibernate-core-4.3.4.Final.jar:4.3.4.Final]
    at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:190) ~[hibernate-core-4.3.4.Final.jar:4.3.4.Final]
    at org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch.addToBatch(NonBatchingBatch.java:62) ~[hibernate-core-4.3.4.Final.jar:4.3.4.Final]
    at org.hibernate.persister.entity.AbstractEntityPersister.update(AbstractEntityPersister.java:3281) ~[hibernate-core-4.3.4.Final.jar:4.3.4.Final]
    at org.hibernate.persister.entity.AbstractEntityPersister.updateOrInsert(AbstractEntityPersister.java:3183) ~[hibernate-core-4.3.4.Final.jar:4.3.4.Final]
    at org.hibernate.persister.entity.AbstractEntityPersister.update(AbstractEntityPersister.java:3525) ~[hibernate-core-4.3.4.Final.jar:4.3.4.Final]
    at org.hibernate.action.internal.EntityUpdateAction.execute(EntityUpdateAction.java:158) ~[hibernate-core-4.3.4.Final.jar:4.3.4.Final]
    at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:461) ~[hibernate-core-4.3.4.Final.jar:4.3.4.Final]
    at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:347) ~[hibernate-core-4.3.4.Final.jar:4.3.4.Final]
    at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:350) ~[hibernate-core-4.3.4.Final.jar:4.3.4.Final]
    at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:56) ~[hibernate-core-4.3.4.Final.jar:4.3.4.Final]
    at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1222) ~[hibernate-core-4.3.4.Final.jar:4.3.4.Final]
    at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:425) ~[hibernate-core-4.3.4.Final.jar:4.3.4.Final]
    at org.hibernate.engine.transaction.internal.jdbc.JdbcTransaction.beforeTransactionCommit(JdbcTransaction.java:101) ~[hibernate-core-4.3.4.Final.jar:4.3.4.Final]
    at org.hibernate.engine.transaction.spi.AbstractTransactionImpl.commit(AbstractTransactionImpl.java:177) ~[hibernate-core-4.3.4.Final.jar:4.3.4.Final]
    at edu.pitt.sis.exp.colfusion.dal.utils.HibernateUtil.commitTransaction(HibernateUtil.java:137) ~[colfusionserverdal-2.0-SNAPSHOT.jar:?]
    ... 5 more
Caused by: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'log' at row 1
    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4235) ~[mysql-connector-java-5.1.29.jar:?]
    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4169) ~[mysql-connector-java-5.1.29.jar:?]
    at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2617) ~[mysql-connector-java-5.1.29.jar:?]
    at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2778) ~[mysql-connector-java-5.1.29.jar:?]
    at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2834) ~[mysql-connector-java-5.1.29.jar:?]
    at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2156) ~[mysql-connector-java-5.1.29.jar:?]
    at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2441) ~[mysql-connector-java-5.1.29.jar:?]
    at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2366) ~[mysql-connector-java-5.1.29.jar:?]
    at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2350) ~[mysql-connector-java-5.1.29.jar:?]
    at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:147) ~[c3p0-0.9.2.1.jar:0.9.2.1]
    at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:187) ~[hibernate-core-4.3.4.Final.jar:4.3.4.Final]
    at org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch.addToBatch(NonBatchingBatch.java:62) ~[hibernate-core-4.3.4.Final.jar:4.3.4.Final]
    at org.hibernate.persister.entity.AbstractEntityPersister.update(AbstractEntityPersister.java:3281) ~[hibernate-core-4.3.4.Final.jar:4.3.4.Final]
    at org.hibernate.persister.entity.AbstractEntityPersister.updateOrInsert(AbstractEntityPersister.java:3183) ~[hibernate-core-4.3.4.Final.jar:4.3.4.Final]
    at org.hibernate.persister.entity.AbstractEntityPersister.update(AbstractEntityPersister.java:3525) ~[hibernate-core-4.3.4.Final.jar:4.3.4.Final]
    at org.hibernate.action.internal.EntityUpdateAction.execute(EntityUpdateAction.java:158) ~[hibernate-core-4.3.4.Final.jar:4.3.4.Final]
    at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:461) ~[hibernate-core-4.3.4.Final.jar:4.3.4.Final]
    at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:347) ~[hibernate-core-4.3.4.Final.jar:4.3.4.Final]
    at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:350) ~[hibernate-core-4.3.4.Final.jar:4.3.4.Final]
    at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:56) ~[hibernate-core-4.3.4.Final.jar:4.3.4.Final]
    at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1222) ~[hibernate-core-4.3.4.Final.jar:4.3.4.Final]
    at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:425) ~[hibernate-core-4.3.4.Final.jar:4.3.4.Final]
    at org.hibernate.engine.transaction.internal.jdbc.JdbcTransaction.beforeTransactionCommit(JdbcTransaction.java:101) ~[hibernate-core-4.3.4.Final.jar:4.3.4.Final]
    at org.hibernate.engine.transaction.spi.AbstractTransactionImpl.commit(AbstractTransactionImpl.java:177) ~[hibernate-core-4.3.4.Final.jar:4.3.4.Final]
    at edu.pitt.sis.exp.colfusion.dal.utils.HibernateUtil.commitTransaction(HibernateUtil.java:137) ~[colfusionserverdal-2.0-SNAPSHOT.jar:?]
    ... 5 more
```

**Comment by EvgenyKarataev** [comment]
Apparently the type of the log attribute was varchar(255), set it to TEXT, but it was part of the setup script, so it is partially fixed in commit b29a5c79178c97c922302d786f01326ebc698339

Still need to fix it in server code when hibernate generates database and tables, it will put varchar
